<?php


function tweaks_init(){
	drupal_add_js(drupal_get_path('module', 'tweaks') . '/js/tweaks.media.js');
	$css = array(
		'tweaks.media.css',
		'global.css',
	);
	foreach($css as $file){
		drupal_add_css(drupal_get_path('module', 'tweaks') . "/css/$file");
	}
}


function tweaks_form_alter(&$form, &$form_state, $form_id){
	switch($form_id){
	case 'webform_client_form_12':
		$form['#submit'][] = 'fr_tweaks_email_form_submit';
		break;
	}
}


function fr_tweaks_email_form_submit($form, &$form_state){
	module_load_include('php', 'tweaks', 'phpmailer/class.phpmailer');
	$base = $form_state['input']['submitted'];
	$body = '<html>
			<body>
				<p>A new lead lead has been submitted from <strong>'.$base['first_name'].'</strong> On '.date('Y-m-d').'.</p><br/>
				<p>Lead Contact Info:<br/>
				Name: '.$base['first_name'].'<br/>
				Primary Phone: '.$base['phone_number'].'<br/>
				Message: '.$base['message'].'
				</p>
			</body>
		</html>';
	define('GUSER', 'no-reply@fortifiedsecurityservices.com'); // GMail username
	define('GPWD', 'FortifieD!'); // GMail password
	global $error;
	$mail = new PHPMailer();  // create a new object
	$mail->IsSMTP(); // enable SMTP
	$mail->SMTPDebug = 0;  // debugging: 1 = errors and messages, 2 = messages only
	$mail->SMTPAuth = true;  // authentication enabled
	$mail->SMTPSecure = 'ssl'; // secure transfer enabled REQUIRED for GMail
	$mail->Host = 'smtp.gmail.com';
	$mail->Port = 465;
	$mail->Username = GUSER;
	$mail->Password = GPWD;
	$mail->SetFrom('no-reply@fortifiedsecurityservices.com', 'Fortified Security Services');
	$mail->Subject = 'You have a new web lead From '.$base['first_name'].'';
	$mail->Body = $body;
	$mail->IsHTML(true);
	$mail->AddAddress('info@fortifiedsecurityservices.com');
	if(!$mail->Send()) {
		$error = 'Mail error: '.$mail->ErrorInfo;
		$success = 'Failed to notify Customer';
	} else {
		$error = 'Message sent!';
		$success = 'Customer has been notified';
	}
	
}



function tweaks_node_view_alter(&$build){
	if(!empty($build['#bundle']) && $build['#bundle'] == 'landing_page'){
		//$build['field_features']
		if(!empty($build['field_features'])){
			$children = array_intersect_key($build['field_features'], array_flip(element_children($build['field_features'])));
			if(isset($children)){
				foreach($children as $delta => $val){
					$markup  = '<li class="feature-li">';
					$markup .= '<span class="glyphicon glyphicon-ok"></span>';
					$markup .= $val['#markup'];
					$markup .= '</li>';
					$build['field_features'][$delta]['#markup'] = $markup;
				}
			}
		}
	}
}
