<?php

function ipdatatel_customer_field_list(){
	return array(
		'user_id' => array(
			'label' => t('User Id'),
		),
		'service_plan' => array(
			'label' => t('Service Plan'),
		),
		'service_plan_id' => array(
			'label' => t('Service Plan Id'),
		),
		'company_name' => array(
			'label' => t('Company Name'),
		),
		'name_first' => array(
			'label' => t('First Name'),
		),
		'name_last' => array(
			'label' => t('Last Name'),
		),
		'email' => array(
			'label' => t('Email'),
		),
		'celltext' => array(
			'label' => t('Cellphone Number'),
		),
		'phone_pri_contact' => array(
			'label' => t('Primeary Contact Number'),
		),
		'phone_pri_ct' => array(
			'label' => t('Primary Conact Type'),
		),
		'phone_sec_contact' => array(
			'label' => t('Secondary Contact Number'),
		),
		'phone_sec_ct' => array(
			'label' => t('Secondary Conact Type'),
		),
		'address_1' => array(
			'label' => t('Street Adress'),
		),
		'address_2' => array(
			'label' => t('Alternative Street Adress'),
		),
		'st_number' => array(
			'label' => t('Street Number'),
		),
		'st_name' => array(
			'label' => t('Street Name'),
		),
		'city' => array(
			'label' => t('City'),
		),
		'state' => array(
			'label' => t('State'),
		),
		'zip_code' => array(
			'label' => t('Postal Code'),
		),
		'contact_type' => array(
			'label' => t('Contact Type'),
		),
		'co_ph_url' => array(
			'label' => t('Company Phone Number'),
		),
		'co_ph_pri' => array(
			'label' => t('Primary Company Phone Number'),
		),
		'co_ph_sec' => array(
			'label' => t('Alternative Company Phone Number'),
		),
		'co_ph_sales' => array(
			'label' => t('Company Sales Number'),
		),
		'co_ph_service' => array(
			'label' => t('Company Service Number'),
		),
		'co_ph_billing' => array(
			'label' => t('Company Billing Number'),
		),
	);
}